apiVersion: v1
kind: ConfigMap
metadata:
  name: my-prometheus-server
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm      
  annotations:
    meta.helm.sh/release-name: my-prometheus  
    meta.helm.sh/release-namespace: default  
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
